In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_2018 = pd.read_excel("cleaned 2018.xlsx")
df_2019 = pd.read_excel("cleaned 2019.xlsx")
df_2020 = pd.read_excel("cleaned 2020.xlsx")
df_2021 = pd.read_excel("cleaned 2021.xlsx")

In [3]:
df_2018.dropna(inplace=True)
df_2018.reset_index(drop=True, inplace=True)

df_2019.dropna(inplace=True)
df_2019.reset_index(drop=True, inplace=True)

df_2020.dropna(inplace=True)
df_2020.reset_index(drop=True, inplace=True)

df_2021.dropna(inplace=True)
df_2021.reset_index(drop=True, inplace=True)

In [4]:
# Adding column year

Year = ["2018" for i in range(df_2018.shape[0])]
df_2018["Year"] = Year

Year = ["2019" for i in range(df_2019.shape[0])]
df_2019["Year"] = Year

Year = ["2020" for i in range(df_2020.shape[0])]
df_2020["Year"] = Year

Year = ["2021" for i in range(df_2021.shape[0])]
df_2021["Year"] = Year

In [5]:
data = [df_2018, df_2019, df_2020, df_2021]
df_main = pd.concat(data)

In [6]:
df_main

,Company/Brand,Sector,Stage,Amount($),What it does,City,Sub city,Year,Founded,Founders,Investor
0,TheCollegeFever,Brand Marketing,Seed,250000.0,"TheCollegeFever is a hub for fun, fiesta and f...",Bangalore,Karnataka,2018,NaN,NaN,NaN
1,Happy Cow Dairy,Agriculture,Seed,40000000.0,A startup which aggregates milk from dairy far...,Mumbai,Maharashtra,2018,NaN,NaN,NaN
2,MyLoanCare,Credit,Series A,65000000.0,Leading Online Loans Marketplace in India,Gurgaon,Haryana,2018,NaN,NaN,NaN
3,PayMe India,Financial Services,Angel,2000000.0,PayMe India is an innovative FinTech organizat...,Noida,Uttar Pradesh,2018,NaN,NaN,NaN
4,Eunimart,E-Commerce Platforms,Seed,0.0,Eunimart is a one stop solution for merchants ...,Hyderabad,Andhra Pradesh,2018,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1201,Gigforce,Staffing & Recruiting,Pre-series A,3000000.0,A gig/on-demand staffing company.,Gurugram,NaN,2021,2019,"Chirag Mittal, Anirudh Syal",Endiya Partners
1202,Vahdam,Food & Beverages,Series D,20000000.0,VAHDAM is among the world’s first vertically i...,New Delhi,NaN,2021,2015,Bala Sarda,IIFL AMC
1203,Leap Finance,Financial Services,Series C,55000000.0,International education loans for high potenti...,Bangalore,NaN,2021,2019,"Arnav Kumar, Vaibhav Singh",Owl Ventures
1204,CollegeDekho,EdTech,Series B,26000000.0,"Collegedekho.com is Student’s Partner, Friend ...",Gurugram,NaN,2021,2015,Ruchir Arora,"Winter Capital, ETS, Man Capital"
1205,WeRize,Financial Services,Series A,8000000.0,India’s first socially distributed full stack ...,Bangalore,NaN,2021,2019,"Vishal Chopra, Himanshu Gupta","3one4 Capital, Kalaari Capital"

In [30]:
df_main["Sector"] = df_main["Sector"].replace('Fintech', "FinTech")
df_main["Sector"] = df_main["Sector"].replace('Edtech', "EdTech")

In [32]:
file_name = "main_df.xlsx"

df_main.to_excel(file_name)